/*---------------游酷SDK接入----------------- *create by batcel at 2017-12-04 */ #if UKGAME_SDKusing System.Runtime.InteropServices;using UnityEngine;using XLua;[Hotfix]public class CUKGameSDK{    public static bool bUKPayTestPrice = false;#if UNITY_IOS    const uint UKGMAEAPPID = 82;    const string UKGAMEKEY_APP = "lreIkopP1mD0C0Af";  //(SDK中的789GAMESDK_APPKEY)    const string UKGAMEKEY_API = "4ntj34m5Qsl1kkqO";  //(充值回调接口使用)    [DllImport("__Internal")]    private static extern void UKGame_Login(string userunionidstr);    [DllImport("__Internal")]    private static extern void UKGame_Logout();    [DllImport("__Internal")]    public static extern void UKGame_ShowAppUpdateTips(string urlstring);    [DllImport("__Internal")]    private static extern void UKGame_LgoinWithQ(string lgoinaccount, string lgoinname, string playerlgoinId,string productId);#endif#if UNITY_ANDROID    const uint UKGMAEAPPID = 83;    const string UKGAMEKEY_APP = "RbyyHxEH7F2lXC9q";  //(SDK中的789GAMESDK_APPKEY)    const string UKGAMEKEY_API = "uNhaywBsSw3q9Dlt";  //(充值回调接口使用)
    static bool bUKGameSDKInit = false;    private static AndroidJavaObject UKGameActivity = null;    /// <summary>    /// 获取ukGameSDK Activity    /// </summary>    /// <returns></returns>    public  static AndroidJavaObject GetUKGameActivity()    {        if (UKGameActivity == null)            InitUKGameActivity();        return UKGameActivity;    }    /// <summary>    /// 初始ukGameSDK Activity    /// </summary>    private static void InitUKGameActivity()    {        if(UKGameActivity == null)        {            AndroidJavaClass unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer");            UKGameActivity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");          }    }    /// <summary>    /// 游酷平台登陆    /// </summary>    /// <param name="unionid"></param>    private static void  UKGame_Login(string unionid)    {        if (UKGameActivity == null)            InitUKGameActivity();        if (bUKGameSDKInit == false)
        {
            bUKGameSDKInit = true;
            UKGameActivity.Call("UKGameSDK_Init");
        }
        UKGameActivity.Call("UKGameSDK_Login", unionid);    }    /// <summary>    /// 游酷平台登出    /// </summary>    private static void UKGame_Logout()    {        if (UKGameActivity == null)            InitUKGameActivity();        UKGameActivity.Call("UKGameSDK_Logout");    }    /// <summary>    /// 游酷平台支付    /// </summary>    /// <param name="itemprice"></param>    /// <param name="itemname"></param>    /// <param name="extendparam"></param>    private static void UKGame_Pay(string itemprice,string itemname,string playeritemId)    {        if (UKGameActivity == null)            InitUKGameActivity();        UKGameActivity.Call("UKGameSDK_Pay",itemprice,itemname, playeritemId);    }#endif    public static void UKPlatform_Login()    {         UKGame_Login("");
         //AlipayWeChatPay.GetAndroidActivity().Call("UKGameSDK_Login","1");    }    public static void UKPlatform_LogOut()    {        UKGame_Logout();    }    public static void UKPlatform_Pay(string itemprice, string itemname, string playeritemId, string productId)    {        //CCustomDialog.OpenCustomWaitUI(1107);
        if (bUKPayTestPrice)
            itemprice = "0.01";

#if UNITY_IOS       UKGame_LgoinWithQ(itemprice, itemname, playeritemId, productId);
#endif
#if UNITY_ANDROID         UKGame_Pay(itemprice, itemname, playeritemId);#endif    }}#endif